name: remote ssh command
on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using private key
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                    cd /container/wpurun/eoty2024-landingpage 
                    sudo git reset --hard HEAD
                    sudo git clean -f -d
                    sudo git pull
                    sudo npm install
                    sudo npm run build

